### ISSUE TITLE
BrowsName and NodId unicity

### ISSUE THREAD

**Issue by zoheirdib** [technosoftware-gmbh/opcua-solution-net-samples#12]
**Type of Issue**
 [ ] Question [ ] Help wanted

# Expected Behavior

I try to reproduce the configuration below

- EquipementA (folder)
              - Temperature (variable)
- EquipementB (folder)
              - Temperature (variable)
        
## Steps to Reproduce

Approach 1
I try using the following calls to create the arborescence of the exemple (schematic code)

var root_EquipementA  = CreateFolderState(null, "EquipementA", new LocalizedText("en", "EquipementA"), new LocalizedText("en", "Root folder of " + Namespaces.Exemple));

var node_EquipementA_Temperature  = CreateVariable(root_EquipementA  , "Temperature", "Temperature", GetTypeFromTag(tag.Type), GetValueRankTypeFromString(tag.Type), GetTagValue(tag.Type, tag.InitialValue));

var root_EquipementB  = CreateFolderState(null, "EquipementB", new LocalizedText("en", "EquipementB"), new LocalizedText("en", "Root folder of " + Namespaces.Exemple));

var node_EquipementB_Temperature  = CreateVariable(root_EquipementB  , "Temperature", "Temperature", GetTypeFromTag(tag.Type), GetValueRankTypeFromString(tag.Type), GetTagValue(tag.Type, tag.InitialValue));

I expected to have a unique NodeId for the nodes root_EquipementA  and root_EquipementB  but when i look at the generated nodeId i found that the NodeID look the same : 
root_EquipementA : ns=2;s=Temperature
root_EquipementB : ns=2;s=Temperature

Approach 2
I try another approche by concatenate the name of the parent folder to the name of the attribut in the brownsname when i create the attribut

var root_EquipementA  = CreateFolderState(null, "EquipementA", new LocalizedText("en", "EquipementA"), new LocalizedText("en", "Root folder of " + Namespaces.Exemple));

var node_EquipementA_Temperature  = CreateVariable(root_EquipementA  , "EquipementA.Temperature", "Temperature", GetTypeFromTag(tag.Type), GetValueRankTypeFromString(tag.Type), GetTagValue(tag.Type, tag.InitialValue));

var root_EquipementB  = CreateFolderState(null, "EquipementB", new LocalizedText("en", "EquipementB"), new LocalizedText("en", "Root folder of " + Namespaces.Exemple));

var node_EquipementB_Temperature  = CreateVariable(root_EquipementB  , "EquipementB.Temperature", "Temperature", GetTypeFromTag(tag.Type), GetValueRankTypeFromString(tag.Type), GetTagValue(tag.Type, tag.InitialValue));

the generated nodeId for the seconde approach lookes unique.
root_EquipementA : ns=2;s=EquipementA.Temperature
root_EquipementB : ns=2;s=EquipementB.Temperature

My question : 
what is the relation ship between brownName and genrated nodeID for the nodes and how may i garanti the unicity of my the node id in the adresse space. In case when clients to suscribe to the températeur of equipementA andn B independently.

Thank you in advance.

Zoheir DIB

**Comment by technosoftware** [comment]
The browseName must be unique. In our samples you find a similar solution as your Approach 2 by adding the root folder name + "_"  + name.

**Comment by zoheirdib** [comment]
Thank you for your response.

When using approache 2 the path of browse name to browse the node "node_EquipementA_Temperature" is : 
/2:EquipementA/2:EquipementA.Temperature

For our purpose, we need to have a path like : 
/2:EquipementA/2:Temperature

To achieve this behavior we use the approach 1 to generate the browseName path and for the nodeId we plan to set the attribute "NodeId" of the created node manually instead of using the generated one like following :

var root_EquipementA = CreateFolderState(null, "EquipementA", new LocalizedText("en", "EquipementA"), new LocalizedText("en", "Root folder of " + Namespaces.Exemple));

var node_EquipementA_Temperature = CreateVariable(root_EquipementA , "Temperature", "Temperature", GetTypeFromTag(tag.Type), GetValueRankTypeFromString(tag.Type), GetTagValue(tag.Type, tag.InitialValue));

node_EquipementA_Temperature.NodeId = new NodeID ("EquipementA.Temperature", NameSpaceIndex);

Do you think this is good practice ? is it safe to override the generated NodeId with another one like illustrated below ?

Thanks you in advance.

Zoheir DIB

**Comment by technosoftware** [comment]
According the specification:

1. The NodeID must be unique. See [here](https://reference.opcfoundation.org/v104/Core/docs/Part3/5.2.2/)
2. The BrowseName must not be unique. See [here](https://reference.opcfoundation.org/v104/Core/docs/Part3/5.2.4/)

So your initial approach 2 should work. I can't test your code directly because it seems it might be based on older versions and contains additional missing methods.

**Comment by technosoftware** [comment]
Probably question answered
