### ISSUE TITLE
.NET 6 support for UA Server?

### ISSUE THREAD

**Issue by TimCorwinCytiva** [technosoftware-gmbh/opcua-solution-net-samples#22]
I see the actual Technosoftware.UaSolution.UaServer package on nuget is tagged for .NET 6, but the README.md specifically mentions .NET 6 for the client, but not the server.
Does the UA server support a .NET 6 runtime? if not, is there an ETA?

**Comment by technosoftware** [comment]
This is a mistake in the README file. The UA server and the UA client supports .NET 6 already and the libraries are included in the packages.

**Comment by TimCorwinCytiva** [comment]
thanks!
