### ISSUE TITLE
Client application hangs during application instance certificate check

### ISSUE THREAD

**Issue by fjanela** [technosoftware-gmbh/opcua-solution-net-samples#48]
If an application instance already has a certificate created on the 'certs' and 'private' folders on the certificate store, the client application hangs with the following message on the trace file:

************************* Logging started at 08/31/2022 09:41:02
08/31/2022 09:41:02.570 Checking application instance certificate.

The exception method thrown by method CheckApplicationInstanceCertificateAsync is 'Could not load certificate: Cannot access certificate private key.'

If the certificate is removed from these folders, the client application works as expected.

Using OPC UA Client version 2.4.3

**Comment by technosoftware** [comment]
For me not reproducible with the Simulation Sample Client (.NET 6.0, Windows 11) and self signed certificate:

1st run:
08/31/2022 17:11:46.732 Checking application instance certificate.
08/31/2022 17:11:46.735 Creating application instance certificate.
08/31/2022 17:11:47.078 Adding application certificate to trusted peer store. [CN=SampleCompany OPC UA Sample Client, C=CH, S=Aargau, O=SampleCompany, DC=technosoftware] [59A4CE663D1D351B5E715485DB06C71C335F72D2]
08/31/2022 17:11:47.079 Added application certificate to trusted peer store.
08/31/2022 17:11:47.129 Imported the PFX private key for [59A4CE663D1D351B5E715485DB06C71C335F72D2].
08/31/2022 17:11:47.134 Certificate created for urn:technosoftware:SampleCompany:SampleClient. [CN=SampleCompany OPC UA Sample Client, C=CH, S=Aargau, O=SampleCompany, DC=technosoftware] [59A4CE663D1D351B5E715485DB06C71C335F72D2]

2nd run:
08/31/2022 17:15:17.539 Imported the PFX private key for [59A4CE663D1D351B5E715485DB06C71C335F72D2].
08/31/2022 17:15:17.547 Checking application instance certificate.
08/31/2022 17:15:17.564 Imported the PFX private key for [59A4CE663D1D351B5E715485DB06C71C335F72D2].
08/31/2022 17:15:17.565 Check certificate: [CN=SampleCompany OPC UA Sample Client, C=CH, S=Aargau, O=SampleCompany, DC=technosoftware] [59A4CE663D1D351B5E715485DB06C71C335F72D2]
08/31/2022 17:15:17.567 Check application instance certificate. [CN=SampleCompany OPC UA Sample Client, C=CH, S=Aargau, O=SampleCompany, DC=technosoftware] [59A4CE663D1D351B5E715485DB06C71C335F72D2]
08/31/2022 17:15:17.607 Using the ApplicationUri: urn:technosoftware:SampleCompany:SampleClient

**Comment by technosoftware** [comment]
We might have an idea what the root cause is, but it would be helpful if we could reproduce it.

Do you have a simple example or some information on how this application certificate was created? Also used OS and .NET version.

**Comment by fjanela** [comment]
Traced the issue to a poorly formatted subject name on the ApplicationCertificate configuration section.
If the subject name node contains a value with spaces between the attribute name and attribute value, for instance <SubjectName>CN = Test OPC UA Client</SubjectName>, then on first run the certificate is created but on the second run the created certificate is not considered valid. Removing the spaces between the attribute name and attribute value on the subject name node (<SubjectName>CN=Test OPC UA Client</SubjectName>) and deleting the certificate folders on the certificate store allows an appropriate certificate to be created and reused on the second run.

Although not technically a bug, it would be nice for the first run to throw an exception and prevent an unusable certificate from being created.

Thanks for you help.

**Comment by technosoftware** [comment]
Next version will include an improved handling of the application certificate. Problems are blanks between the key, e.g. CN and the "=" because then the entry of that key is not found and a default is added.
